### ISSUE TITLE
Error when locale is different from English.

### ISSUE THREAD

**Issue by mreduar** [svnwa/InertiaVuePaginator#2]
When you have configured the locale different from `en` it will give a validation error from the `inertia-link` component because it is passing a null href. This is because the `isFirstOrLastOrDots` method is validating if `label.includes('Next') || label.includes('Previous')`
As it is a different locale this will no longer be included.

**Comment by svnwa** [comment]
You're right. Didn't think about that. Shouldn't be a problem with these changes anymore 824f74279a5dcb5520581890b583edddaeffa6fd
